apiVersion: v1
kind: ConfigMap
metadata:
  name: data-intake-configmap
data:
  FLASK_ENV: "staging"
  APP_NAME: "saludtechalpes-data-intake-service"
  PULSAR_HOST: "pulsar-broker"
  BROKER_HOST: "broker"
  BROKER_PORT: "6650"